<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="model.Patient"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.servlet.http.HttpSession" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="private" />
<meta http-equiv="x-ua-Compatible" content="IE=edge" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta name="viewport"
	content="width=device-width, initial-scale=0.5, maximum-scale=5.0, user-scalable=1" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="author" content="Justinmind S.L." />
<meta name="description"
	content="Generated by Justinmind on Thu Nov 24 16:22:14 EST 2011" />
<title>project_Latest We_Care_2011-11-15_10h55m17s -
Admit_Patient_Bed</title>
</head>
<body>
<%
	Patient patient = (Patient)session.getAttribute("patient"); 
	ArrayList<String> beds = (ArrayList<String>)session.getAttribute("beds");
%>
<div id="s-8c8b18d6-792d-4be1-a008-af108ba66400"><input
	id="screenName" type="hidden" value="Admit_Patient_Bed" /><input
	id="canvases" type="hidden"
	value="s-8c8b18d6-792d-4be1-a008-af108ba66400?t-70f2be6c-31aa-4006-9a58-4bf50f104708" />
<link rel="stylesheet" charset="utf-8"
	href="css/screens/Admit_Patient_Bed.css" />
<link rel="stylesheet" charset="utf-8"
	href="css/templates/Nurse%20Template.css" />
<!--[if IE]><link rel="stylesheet" charset="utf-8" href="css/screens/Admit_Patient_Bed-ie.css"/><link rel="stylesheet" charset="utf-8" href="css/templates/Nurse%20Template-ie.css"/><![endif]-->
<div
	class="t-70f2be6c-31aa-4006-9a58-4bf50f104708 template firer commentable"><img
	id="t-Image_1" class="image firer commentable" alt="image"
	src="images/19-%20jp_clipboard_image.png" /><img id="t-Image_2"
	class="image firer commentable" alt="image"
	src="images/0-%20we%20care.gif" />
<div id="t-Line_1" class="horizontalline firer commentable"></div>
<div id="t-Line_2" class="horizontalline firer commentable"></div>
<div id="t-Label_2" class="label firer commentable">© 2011 We
Care. All Rights Reserved</div>
				<form action="Logout" method="post">
			<div id="t-Button_8" class="button firer click commentable"><input type="submit" value="Logout" /></div></form>
			<form action="Nurse_Login.html" method="post">
			<div id="t-Button_9" class="button firer click commentable"><input type="submit" value="Home" /></div></form>
</div>
<div
	class="s-8c8b18d6-792d-4be1-a008-af108ba66400 screen firer commentable">
<div id="s-Label_27" class="label firer commentable">Admit Patient</div>
<form action="GetBedsForRoom" method="post">
<div id="s-Button_1" class="button firer commentable"><input type="submit" value="Submit"/></div>
<img id="s-Image_2" class="image firer commentable" alt="image"
	src="images/0-%20images%20(3).jpg" />
<div id="s-Rectangle_2" class="rectangle firer commentable"></div>
<div id="s-Label_31" class="label firer commentable">Bed #</div>

<div id="s-Rectangle_1" class="rectangle firer commentable"></div>
<div id="s-Rich_text_1" class="richtext firer commentable">
<div id="s-Rich_text_1-container">
<table class="collapse" style="height: 100%; width: 100%;" summary="">
	<tbody>
		<tr>
			<td><span id="s-Rich_text_1_0"><%=patient.getFirstName()%> <%=patient.getLastName() %></span></td>
		</tr>
	</tbody>
</table>
</div>
</div>
<div id="s-Label_5" class="label firer commentable">Name</div>
<div id="s-Rich_text_5" class="richtext firer commentable">
<div id="s-Rich_text_5-container">
<table class="collapse" style="height: 100%; width: 100%;" summary="">
	<tbody>
		<tr>
			<td><span id="s-Rich_text_5_0"><%=patient.getHealthInsuranceNumber() %></span></td>
		</tr>
	</tbody>
</table>
</div>
</div>
<div id="s-Label_6" class="label firer commentable">Health
Insurance Number</div>
<div id="s-Label_7" class="label firer commentable">Date of Birth</div>
<div id="s-Label_8" class="label firer commentable">Registration
Date</div>
<div id="s-Rich_text_3" class="richtext firer commentable">
<div id="s-Rich_text_3-container">
<table class="collapse" style="height: 100%; width: 100%;" summary="">
	<tbody>
		<tr>
			<td><span id="s-Rich_text_3_0"><%=patient.getDOB() %></span></td>
		</tr>
	</tbody>
</table>
</div>
</div>
<div id="s-Rich_text_4" class="richtext firer commentable">
<div id="s-Rich_text_4-container">
<table class="collapse" style="height: 100%; width: 100%;" summary="">
	<tbody>
		<tr>
			<td><span id="s-Rich_text_4_0"><%=patient.getRegistrationDate() %></span></td>
		</tr>
	</tbody>
</table>
</div>
</div>

			<div id="s-Input_1" class="inputtext firer commentable">

<select name="Bed">
<% for (int i = 0; i < beds.size(); i++) { %>
<option value="<%=beds.get(i)%>"> <%= beds.get(i) %></option>
<% } %>
</select></div></form>
				<input maxlength="100" />
			</div>
		</div>
	
</body>
</html>