<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="model.Patient"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.servlet.http.HttpSession" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="private" />
<meta http-equiv="x-ua-Compatible" content="IE=edge" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta name="viewport"
	content="width=device-width, initial-scale=0.5, maximum-scale=5.0, user-scalable=1" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="author" content="Justinmind S.L." />
<meta name="description"
	content="Generated by Justinmind on Thu Nov 24 18:37:40 EST 2011" />
<title>changed prototype - Error_New Patient_Registration</title>
</head>
<body>
	<div id="s-8936ac6c-100c-48dc-8f13-1c1e372ae8c3">
		<input id="screenName" type="hidden"
			value="Error_New Patient_Registration" /><input id="canvases"
			type="hidden"
			value="s-8936ac6c-100c-48dc-8f13-1c1e372ae8c3?t-70f2be6c-31aa-4006-9a58-4bf50f104708" />
		<link rel="stylesheet" charset="utf-8"
			href="css/screens/Error_New%20Patient_Registration.css" />
		<link rel="stylesheet" charset="utf-8"
			href="css/templates/Nurse%20Template.css" />
		<!--[if IE]><link rel="stylesheet" charset="utf-8" href="css/screens/Error_New%20Patient_Registration-ie.css"/><link rel="stylesheet" charset="utf-8" href="css/templates/Nurse%20Template-ie.css"/><![endif]-->
		<div
			class="t-70f2be6c-31aa-4006-9a58-4bf50f104708 template firer commentable">
			<img id="t-Image_1" class="image firer commentable" alt="image"
				src="images/19-%20jp_clipboard_image.png" /><img id="t-Image_2"
				class="image firer commentable" alt="image"
				src="images/0-%20we%20care.gif" />
			<div id="t-Line_1" class="horizontalline firer commentable"></div>
			<div id="t-Line_2" class="horizontalline firer commentable"></div>
			<div id="t-Label_2" class="label firer commentable">© 2011 We
				Care. All Rights Reserved</div>
			<form action="Logout" method="post">
			<div id="t-Button_8" class="button firer click commentable"><input type="submit" value="Logout" /></div></form>
			<form action="Nurse_Login.html" method="post">
			<div id="t-Button_9" class="button firer click commentable"><input type="submit" value="Home" /></div></form>
		</div>
		<div
			class="s-8936ac6c-100c-48dc-8f13-1c1e372ae8c3 screen firer commentable">
			<div id="s-Label_22" class="label firer commentable">Some
				fields are missing. Please verify again</div>
			<div id="s-Label_1" class="label firer commentable">First Name</div>
			<div id="s-Input_1" class="inputtext firer commentable">
				<input name="First_Name" type="text" maxlength="100" />
			</div>
			<div id="s-Label_2" class="label firer commentable">Last Name</div>
			<div id="s-Input_2" class="inputtext firer commentable">
				<input name="Last_Name" type="text" maxlength="100" />
			</div>
			<div id="s-Label_3" class="label firer commentable">Health
				Insurance Number</div>
			<div id="s-Input_3" class="inputtext firer commentable">
				<input name="Health_Insurance_Number" type="text" maxlength="100" />
			</div>
			<div id="s-Label_4" class="label firer commentable">DOB</div>
			<div id="s-Label_5" class="label firer commentable">Emergency
				Contact Name</div>
			<div id="s-Input_4" class="inputtext firer commentable">
				<input name="Emergency_Contact_Person"  type="text" maxlength="100" />
			</div>
			<div id="s-Label_6" class="label firer commentable">Registration
				Date</div>
			<div id="s-Label_8" class="label firer commentable">Family
				Doctor Name</div>
			<div id="s-Input_5" class="inputtext firer commentable">
				<input name="Family_Doctor_Name" type="text" maxlength="100" />
			</div>
			<div id="s-Label_10" class="label firer commentable">Province</div>
			<div id="s-Input_6" class="inputtext firer commentable">
				<input name="Province" type="text" maxlength="100" />
			</div>
			<div id="s-Label_11" class="label firer commentable">Country</div>
			<div id="s-Input_7" class="inputtext firer commentable">
				<input name="Country" type="text" maxlength="100" />
			</div>
			<div id="s-Label_12" class="label firer commentable">Address</div>
			<div id="s-Input_8" class="inputtext firer commentable">
				<input name="Address" type="text" maxlength="100" />
			</div>
			<div id="s-Label_13" class="label firer commentable">Contact
				Number</div>
			<div id="s-Input_9" class="inputtext firer commentable">
				<input name="Contact_Number" type="text" maxlength="100" />
			</div>
			<div id="s-Label_15" class="label firer commentable">Gender M
				<input id="s-Radio_button_17" class="radiobutton firer commentable" type="radio" name="gender" value="male" checked/> F
				<input id="s-Radio_button_18" class="radiobutton firer commentable" type="radio" name="gender"
				value="female" /></div>
			<div id="s-Label_16" class="label firer commentable">City</div>
			<div id="s-Label_19" class="label firer commentable">Family
				Doctor Contact Number</div>
			<div id="s-Input_10" class="inputtext firer commentable">
				<input name="Family_Doctor_Contact_Number" type="text" maxlength="100" />
			</div>
			<div id="s-Button_2" class="button firer commentable"><input type="submit" value="Submit"/></div>
			<div id="s-Label_20" class="label firer commentable">Medical
				History</div>
			<div id="s-Label_21" class="label firer commentable">Personal
				Data</div>
			<div id="s-Label_17" class="label firer commentable">Yes</div>
			<div id="s-Label_18" class="label firer commentable">No</div>
			<input id="s-Radio_button_9" class="radiobutton firer commentable"
				type="radio" name="heart" value="yes" /><input id="s-Radio_button_10"
				class="radiobutton firer commentable" type="radio" name="heart"
				value="no" />
			<div id="s-Rich_text_1" class="richtext firer commentable">
				<div id="s-Rich_text_1-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_1_0">Heart or circulatory
										disorders</span><span id="s-Rich_text_1_1"><br />eg high blood
										pressure, angina/chest pains, heart attack, heart failure,
										abnormal heart beat, aneurysms, or varicose veins</span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		<input id="s-Radio_button_11" class="radiobutton firer commentable"
				type="radio" name="endocrine" value="yes" /><input
				id="s-Radio_button_12" class="radiobutton firer commentable"
				type="radio" name="endocrine" value="no" />
			<div id="s-Rich_text_7" class="richtext firer commentable">
				<div id="s-Rich_text_7-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_7_0">Endocrine (glandular)
										disorders<br />
								</span><span id="s-Rich_text_7_1">eg Diabetes (Type 1 or Type
										2), thyroid problems, or obesity</span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<input id="s-Radio_button_13" class="radiobutton firer commentable"
				type="radio" name="breathing" value="yes" /><input
				id="s-Radio_button_14" class="radiobutton firer commentable"
				type="radio" name="breathing" value="no" />
			<div id="s-Rich_text_8" class="richtext firer commentable">
				<div id="s-Rich_text_8-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_8_0">Breathing or
										respiratory disorders<br />
								</span><span id="s-Rich_text_8_1">eg Shortness of breath,
										asthma, COPD, chest infections, pneumonia, bronchitis,
										tuberculosis or allergies (including hayfever and anaphylaxis)</span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<input id="s-Radio_button_15" class="radiobutton firer commentable"
				type="radio" name="stomach" value="yes" /><input
				id="s-Radio_button_16" class="radiobutton firer commentable"
				type="radio" name="stomach" value="no" />
			<div id="s-Rich_text_9" class="richtext firer commentable">
				<div id="s-Rich_text_9-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_9_0">Stomach, intestines,
										liver or gall bladder<br />
								</span><span id="s-Rich_text_9_1">eg stomach
										inflammation/ulcers, irritable bowel, Crohn's disease,
										colitis, change in bowel habits, abdominal pain,
										haemorrhoids/piles, pancreatitis, liver inflammation,
										cirrhosis, gall stones or hernias</span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<div id="s-Label_23" class="label firer commentable">Other</div>
			<textarea id="s-Input_16" name="other" class="textarea firer commentable"></textarea>
			<div id="s-Label_27" class="label firer commentable">New
				Patient Registration</div>

			<div id="s-Input_15" class="inputtext firer commentable">
				<input name="city" type="text" maxlength="100" />
			</div>
			<div id="s-Label_28" class="label firer commentable">Postal
				Code</div>
			<div id="s-Input_16" class="inputtext firer commentable">
				<input name="Postal_Code" type="text" maxlength="100" />
			</div>
			<div id="s-Label_29" class="label firer commentable">Emergency
				Contact Number</div>
			<div id="s-Input_17" class="inputtext firer commentable">
				<input name="Emergency_Contact_Number" type="text" maxlength="100" />
			</div>


			<div id="s-Input_12" class="inputtext firer commentable">
				<input name="year" type="text" maxlength="100" />
			</div>
			<div id="s-Input_13" class="inputtext firer commentable">

<select name="Month">
<option value="01">Jan</option>
<option value="02">Feb</option>
<option value="03">Mar</option>
<option value="04">Apr</option>
<option value="05">May</option>
<option value="06">Jun</option>
<option value="07">Jul</option>
<option value="08">Aug</option>
<option value="09">Sep</option>
<option value="10">Oct</option>
<option value="11">Nov</option>
<option value="12">Dec</option>
</select>

				<input maxlength="100" />
			</div>
			<div id="s-Input_14" class="inputtext firer commentable">

<select name="date">
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select>

				<input maxlength="100" />
			</div>
			</form>
		</div>
	</div>
</body>
</html>