<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="model.Patient"%>
    <%@ page import="model.Report"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.servlet.http.HttpSession" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="private" />
<meta http-equiv="x-ua-Compatible" content="IE=edge" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta name="viewport"
	content="width=device-width, initial-scale=0.5, maximum-scale=5.0, user-scalable=1" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="author" content="Justinmind S.L." />
<meta name="description"
	content="Generated by Justinmind on Tue Nov 15 17:06:07 EST 2011" />
<title>project_Latest We_Care_2011-11-15_10h55m17s -
	Lawyer_View_Audit</title>
</head>
<body>

<%
	Patient patient = (Patient)session.getAttribute("patientObject"); 
	ArrayList<Report> reportlist = (ArrayList<Report>)session.getAttribute("reports");
%>

	<div id="s-dced80ad-7eda-495c-93e9-8091cef6bc40">
		<input id="screenName" type="hidden" value="Lawyer_View_Audit" /><input
			id="canvases" type="hidden"
			value="s-dced80ad-7eda-495c-93e9-8091cef6bc40?t-294f3646-1408-4be6-966a-1de0d3e78e05" />
		<link rel="stylesheet" charset="utf-8"
			href="css/screens/Lawyer_View_Audit.css" />
		<link rel="stylesheet" charset="utf-8"
			href="css/templates/Lawyer%20Template.css" />
		<!--[if IE]><link rel="stylesheet" charset="utf-8" href="css/screens/Lawyer_View_Audit-ie.css"/><link rel="stylesheet" charset="utf-8" href="css/templates/Lawyer%20Template-ie.css"/><![endif]-->
		<div
			class="t-294f3646-1408-4be6-966a-1de0d3e78e05 template firer commentable">
			<div id="t-Line_1" class="horizontalline firer commentable"></div>
			<img id="t-Image_1" class="image firer commentable" alt="image"
				src="images/143-%20jp_clipboard_image.png" /><img id="t-Image_2"
				class="image firer commentable" alt="image"
				src="images/0-%20we%20care.gif" />
			<div id="t-Line_2" class="horizontalline firer commentable"></div>
			<div id="t-Label_3" class="label firer commentable">© 2011 We
				Care. All Rights Reserved</div>
		    <form action="Logout" method="post">
			<div id="t-Button_8" class="button firer click commentable"><input type="submit" value="Logout" /></div></form>
			<form action="lawyer.html" method="post">
			<div id="t-Button_9" class="button firer click commentable"><input type="submit" value="Home" /></div></form>
		</div>
		<div
			class="s-dced80ad-7eda-495c-93e9-8091cef6bc40 screen firer commentable">
			<div id="s-Rectangle_3" class="rectangle firer commentable"></div>
			<div id="s-Rectangle_2" class="rectangle firer commentable"></div>
			<div id="s-Rectangle_1" class="rectangle firer commentable"></div>
			<div id="s-Label_27" class="label firer commentable">Audit
				Trail</div>
			<div id="s-Rich_text_1" class="richtext firer commentable">
				<div id="s-Rich_text_1-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_1_0"><%=patient.getFirstName()%> <%=patient.getLastName()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_5" class="label firer commentable">Name</div>
			<div id="s-Rich_text_5" class="richtext firer commentable">
				<div id="s-Rich_text_5-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_5_0"><%=patient.getHealthInsuranceNumber() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_6" class="label firer commentable">Health
				Insurance Number</div>
			<div id="s-Rich_text_2" class="richtext firer commentable">
				<div id="s-Rich_text_2-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_2_0"><%=patient.getDOB() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_7" class="label firer commentable">Date of
				Birth</div>
			<div id="s-Rich_text_3" class="richtext firer commentable">
				<div id="s-Rich_text_3-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_3_0"><%=patient.getRegistrationDate() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_8" class="label firer commentable">Registration
				Date</div>
			<div id="s-Rich_text_4" class="richtext firer commentable">
				<div id="s-Rich_text_4-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_4_0"> <%= reportlist.get(0).getDiagnosis() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_11" class="label firer commentable">Diagnosis</div>
			<div id="s-Rich_text_6" class="richtext firer commentable">
				<div id="s-Rich_text_6-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_6_0"> <%= reportlist.get(0).getPrescription()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_12" class="label firer commentable">Prescription</div>
			<div id="s-Label_13" class="label firer commentable">Diagnosis</div>
			<div id="s-Label_14" class="label firer commentable">Prescription</div>
			<div id="s-Button_1" class="button firer commentable">Old
				Report</div>
			<div id="s-Button_2" class="button firer commentable">New
				Report</div>
			<div id="s-Line_1" class="verticalline firer commentable"></div>
			<div id="s-Rich_text_7" class="richtext firer commentable">
				<div id="s-Rich_text_7-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_7_0"><%= reportlist.get(1).getDiagnosis() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_8" class="richtext firer commentable">
				<div id="s-Rich_text_8-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_8_0"> <%= reportlist.get(1).getPrescription()%> </span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</body>
</html>