<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="model.Patient"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.servlet.http.HttpSession" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="private" />
<meta http-equiv="x-ua-Compatible" content="IE=edge" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta name="viewport"
	content="width=device-width, initial-scale=0.5, maximum-scale=5.0, user-scalable=1" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="author" content="Justinmind S.L." />
<meta name="description"
	content="Generated by Justinmind on Sun Nov 20 02:11:30 EST 2011" />
<title>project_Latest We_Care_2011-11-15_10h55m17s -
	Nurse_Edit_Patient_record</title>
</head>
<body>

	<div id="s-ad7bd533-84c1-42a6-a48f-215d65ed5feb">
		<input id="screenName" type="hidden" value="Nurse_Edit_Patient_record" /><input
			id="canvases" type="hidden"
			value="s-ad7bd533-84c1-42a6-a48f-215d65ed5feb?t-70f2be6c-31aa-4006-9a58-4bf50f104708" />
		<link rel="stylesheet" charset="utf-8"
			href="css/screens/Nurse_Edit_Patient_record.css" />
		<link rel="stylesheet" charset="utf-8"
			href="css/templates/Nurse%20Template.css" />
		<!--[if IE]><link rel="stylesheet" charset="utf-8" href="css/screens/Nurse_Edit_Patient_record-ie.css"/><link rel="stylesheet" charset="utf-8" href="css/templates/Nurse%20Template-ie.css"/><![endif]-->
		<div
			class="t-70f2be6c-31aa-4006-9a58-4bf50f104708 template firer commentable">
			<img id="t-Image_1" class="image firer commentable" alt="image"
				src="images/19-%20jp_clipboard_image.png" /><img id="t-Image_2"
				class="image firer commentable" alt="image"
				src="images/0-%20we%20care.gif" />
			<div id="t-Line_1" class="horizontalline firer commentable"></div>
			<div id="t-Line_2" class="horizontalline firer commentable"></div>
			<div id="t-Label_2" class="label firer commentable">© 2011 We
				Care. All Rights Reserved</div>
			<form action="Logout" method="post">
			<div id="t-Button_8" class="button firer click commentable"><input type="submit" value="Logout" /></div></form>
			<form action="Nurse_Login.html" method="post">
			<div id="t-Button_9" class="button firer click commentable"><input type="submit" value="Home" /></div></form>
		</div>
		<div
			class="s-ad7bd533-84c1-42a6-a48f-215d65ed5feb screen firer commentable">
			<div id="s-Rectangle_1" class="rectangle firer commentable"></div>
			<div id="s-Label_1" class="label firer commentable">First Name</div>
			<div id="s-Label_2" class="label firer commentable">Last Name</div>
			<div id="s-Label_3" class="label firer commentable">Health
				Insurance Number</div>
			<div id="s-Label_5" class="label firer commentable">Contact
				Number</div>
			<div id="s-Label_8" class="label firer commentable">Family
				Doctor</div>
			<div id="s-Label_10" class="label firer commentable">Province</div>
			<div id="s-Label_11" class="label firer commentable">Country</div>
			<div id="s-Label_12" class="label firer commentable">Address</div>
			<div id="s-Label_13" class="label firer commentable">Postal
				Code</div>
			<div id="s-Label_16" class="label firer commentable">City</div>
			<div id="s-Label_19" class="label firer commentable">Family
				Doctor Contact Number</div>
			<div id="s-Label_21" class="label firer commentable">Personal
				Data</div>
			<form action="EditPatientPersonalRecord" method="post">	
			<div id="s-Input_2" class="inputtext firer commentable">
				<input name="First_Name" type="text" maxlength="100" />
			</div>
			<div id="s-Input_3" class="inputtext firer commentable">
				<input name="Last_Name" type="text" maxlength="100" />
			</div>
			<div id="s-Input_4" class="inputtext firer commentable">
				<input name="Number" type="text" maxlength="100" />
			</div>
			<div id="s-Input_5" class="inputtext firer commentable">
				<input name="Family_Doctor_Name" type="text" maxlength="100" />
			</div>
			<div id="s-Input_6" class="inputtext firer commentable">
				<input name="Province" type="text" maxlength="100" />
			</div>
			<div id="s-Input_7" class="inputtext firer commentable">
				<input name="Country" type="text" maxlength="100" />
			</div>
			<div id="s-Input_8" class="inputtext firer commentable">
				<input name="Address" type="text" maxlength="100" />
			</div>
			<div id="s-Input_9" class="inputtext firer commentable">
				<input name="Postal_Code" type="text" maxlength="100" />
			</div>
			<div id="s-Input_14" class="inputtext firer commentable">
				<input name="City" type="text" maxlength="100" />
			</div>
			<div id="s-Input_15" class="inputtext firer commentable">
				<input name="Family_Doctor_Number" type="text" maxlength="100" />
			</div>
			<div id="s-Label_27" class="label firer commentable">Edit
				Patient Record</div>
			<div id="s-Button_2" class="button firer commentable"><input type="submit" value="Submit"/></div>
			<div id="s-Rich_text_6" class="richtext firer commentable">
				<div id="s-Rich_text_6-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_6_0"><%= session.getAttribute("healthInsuranceNumber").toString() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_6" class="label firer commentable">Emergency
				Contact Name</div>
			<div id="s-Input_10" class="inputtext firer commentable">
				<input name="Contact_Number" type="text" maxlength="100" />
			</div>
			<div id="s-Label_28" class="label firer commentable">Emergency
				Contact Number</div>
			<div id="s-Input_11" class="inputtext firer commentable">
				<input name="Emergency_Contact_Person" type="text" maxlength="100" />
			</div></form>
		</div>
	</div>
</body>
</html>