<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="model.Patient"%>
    <%@ page import="model.Schedule"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.servlet.http.HttpSession" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="private" />
<meta http-equiv="x-ua-Compatible" content="IE=edge" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta name="viewport"
	content="width=device-width, initial-scale=0.5, maximum-scale=5.0, user-scalable=1" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="author" content="Justinmind S.L." />
<meta name="description"
	content="Generated by Justinmind on Fri Nov 18 19:41:27 EST 2011" />
<title>project_Latest We_Care_2011-11-15_10h55m17s - Select Time</title>
</head>
<body>

<%
	ArrayList<String> availableTimeSlots = (ArrayList<String>)session.getAttribute("availableTimeSlots"); 
%>

	<div id="s-650c5e1c-7816-4735-b95e-15db303b4f43">
		<input id="screenName" type="hidden" value="Select Time" /><input
			id="canvases" type="hidden"
			value="s-650c5e1c-7816-4735-b95e-15db303b4f43?t-70f2be6c-31aa-4006-9a58-4bf50f104708" />
		<link rel="stylesheet" charset="utf-8"
			href="css/screens/Select%20Time.css" />
		<link rel="stylesheet" charset="utf-8"
			href="css/templates/Nurse%20Template.css" />
		<!--[if IE]><link rel="stylesheet" charset="utf-8" href="css/screens/Select%20Time-ie.css"/><link rel="stylesheet" charset="utf-8" href="css/templates/Nurse%20Template-ie.css"/><![endif]-->
		<div
			class="t-70f2be6c-31aa-4006-9a58-4bf50f104708 template firer commentable">
			<img id="t-Image_1" class="image firer commentable" alt="image"
				src="images/19-%20jp_clipboard_image.png" /><img id="t-Image_2"
				class="image firer commentable" alt="image"
				src="images/0-%20we%20care.gif" />
			<div id="t-Line_1" class="horizontalline firer commentable"></div>
			<div id="t-Line_2" class="horizontalline firer commentable"></div>
			<div id="t-Label_2" class="label firer commentable">© 2011 We
				Care. All Rights Reserved</div>
			<form action="Logout" method="post">
			<div id="t-Button_8" class="button firer click commentable"><input type="submit" value="Logout" /></div></form>
			<form action="Nurse_Login.html" method="post">
			<div id="t-Button_9" class="button firer click commentable"><input type="submit" value="Home" /></div></form>
		</div>
		<div
			class="s-650c5e1c-7816-4735-b95e-15db303b4f43 screen firer commentable">
			
			<div id="s-Rectangle_1" class="rectangle firer commentable"></div>
			<div id="s-Label_1" class="label firer commentable">Doctor's
				Name</div>
			<img id="s-Image_1" class="image firer commentable" alt="image"
				src="images/0-%20services_banner_appointment_scheduling.jpg" />
			<div id="s-Rich_text_2" class="richtext firer commentable">
				<div id="s-Rich_text_2-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_2_0"><%= session.getAttribute("doctor") %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_6" class="label firer commentable">Date</div>
			
	        <% for (int i = 0; i < availableTimeSlots.size(); i++) { %>
			<div id="s-Rich_text_<%= (i + 3)%>" class="richtext firer commentable">
				<div id="s-Rich_text_-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_<%= (i+3) %>_0"><%= availableTimeSlots.get(i) %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		    <% } %>
			<div id="s-Label_21" class="label firer commentable">Available
				Time Slots</div>
			<div id="s-Label_27" class="label firer commentable">Book
				Appointment</div>
			<form action="FinalizeAppointment" method="post">
			<div id="s-Button_1" class="button firer commentable"><input type="submit" value="Submit"/></div>
			<div id="s-Rich_text_11" class="richtext firer commentable">
				<div id="s-Rich_text_11-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_11_0"><%=session.getAttribute("date") %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<% for (int j = 0; j < availableTimeSlots.size(); j++) { %>
			<input id="s-Radio_button_<%=(j+1) %>" class="radiobutton firer commentable"
				type="radio" name="timeslot" value="<%= availableTimeSlots.get(j) %>"  />
			<% } %>	</form>
		</div>	
	</div>
</body>
</html>