<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="model.Patient"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.servlet.http.HttpSession" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="private" />
<meta http-equiv="x-ua-Compatible" content="IE=edge" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta name="viewport"
	content="width=device-width, initial-scale=0.5, maximum-scale=5.0, user-scalable=1" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="author" content="Justinmind S.L." />
<meta name="description"
	content="Generated by Justinmind on Sun Nov 20 02:11:31 EST 2011" />
<title>project_Latest We_Care_2011-11-15_10h55m17s -
	Success_Patient_Registration</title>
</head>
<body>

<% Patient patient = (Patient) session.getAttribute("patientObject"); %>

	<div id="s-67b52402-1371-426a-95fd-22eb44297570">
		<input id="screenName" type="hidden"
			value="Success_Patient_Registration" /><input id="canvases"
			type="hidden"
			value="s-67b52402-1371-426a-95fd-22eb44297570?t-70f2be6c-31aa-4006-9a58-4bf50f104708" />
		<link rel="stylesheet" charset="utf-8"
			href="css/screens/Success_Patient_Registration.css" />
		<link rel="stylesheet" charset="utf-8"
			href="css/templates/Nurse%20Template.css" />
		<!--[if IE]><link rel="stylesheet" charset="utf-8" href="css/screens/Success_Patient_Registration-ie.css"/><link rel="stylesheet" charset="utf-8" href="css/templates/Nurse%20Template-ie.css"/><![endif]-->
		<div
			class="t-70f2be6c-31aa-4006-9a58-4bf50f104708 template firer commentable">
			<img id="t-Image_1" class="image firer commentable" alt="image"
				src="images/19-%20jp_clipboard_image.png" /><img id="t-Image_2"
				class="image firer commentable" alt="image"
				src="images/0-%20we%20care.gif" />
			<div id="t-Line_1" class="horizontalline firer commentable"></div>
			<div id="t-Line_2" class="horizontalline firer commentable"></div>
			<div id="t-Label_2" class="label firer commentable">© 2011 We
				Care. All Rights Reserved</div>
			<form action="Logout" method="post">
			<div id="t-Button_8" class="button firer click commentable"><input type="submit" value="Logout" /></div></form>
			<form action="Nurse_Login.html" method="post">
			<div id="t-Button_9" class="button firer click commentable"><input type="submit" value="Home" /></div></form>
		</div>
		<div
			class="s-67b52402-1371-426a-95fd-22eb44297570 screen firer commentable">
			<div id="s-Rectangle_1" class="rectangle firer commentable"></div>
			<div id="s-Label_1" class="label firer commentable">First Name</div>
			<div id="s-Label_2" class="label firer commentable">Last Name</div>
			<div id="s-Label_3" class="label firer commentable">Health
				Insurance Number</div>
			<div id="s-Label_4" class="label firer commentable">DOB</div>
			<div id="s-Label_5" class="label firer commentable">Contact
				Number</div>
			<div id="s-Label_8" class="label firer commentable">Family
				Doctor</div>
			<div id="s-Label_6" class="label firer commentable">Registration
				Date</div>
			<div id="s-Label_10" class="label firer commentable">Province</div>
			<div id="s-Label_11" class="label firer commentable">Country</div>
			<div id="s-Label_12" class="label firer commentable">Address</div>
			<div id="s-Label_13" class="label firer commentable">Postal
				Code</div>
			<div id="s-Label_15" class="label firer commentable">Gender</div>
			<div id="s-Label_16" class="label firer commentable">City</div>
			<div id="s-Label_19" class="label firer commentable">Family
				Doctor Contact Number</div>
			<div id="s-Label_21" class="label firer commentable">Personal
				Data</div>
			<div id="s-Label_27" class="label firer commentable">Patient
				Registration Successful</div>
			<div id="s-Rich_text_1" class="richtext firer commentable">
				<div id="s-Rich_text_1-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_1_0"><%= patient.getFirstName() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_3" class="richtext firer commentable">
				<div id="s-Rich_text_3-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_3_0"><%= patient.getLastName() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_5" class="richtext firer commentable">
				<div id="s-Rich_text_5-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_5_0"><%= patient.getGender() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_6" class="richtext firer commentable">
				<div id="s-Rich_text_6-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_6_0"><%= patient.getHealthInsuranceNumber() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_8" class="richtext firer commentable">
				<div id="s-Rich_text_8-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_8_0"><%= patient.getAddress() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_7" class="richtext firer commentable">
				<div id="s-Rich_text_7-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_7_0"><%= patient.getCity() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_10" class="richtext firer commentable">
				<div id="s-Rich_text_10-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_10_0"><%= patient.getCountry() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_11" class="richtext firer commentable">
				<div id="s-Rich_text_11-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_11_0"><%= patient.getPostalCode() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_12" class="richtext firer commentable">
				<div id="s-Rich_text_12-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_12_0"><%= patient.getProvince() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_13" class="richtext firer commentable">
				<div id="s-Rich_text_13-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_13_0"><%= patient.getContactNumber() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_14" class="richtext firer commentable">
				<div id="s-Rich_text_14-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_14_0"><%= patient.getFamilyDoctorName()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_15" class="richtext firer commentable">
				<div id="s-Rich_text_15-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_15_0"><%= patient.getFamilyDoctorNumber()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_9" class="label firer commentable">Emergency
				Contact Name</div>
			<div id="s-Label_20" class="label firer commentable">Emergency
				Contact Number</div>
			<div id="s-Rich_text_22" class="richtext firer commentable">
				<div id="s-Rich_text_22-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_22_0"><%= patient.getEmergencyContactName()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_23" class="richtext firer commentable">
				<div id="s-Rich_text_23-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_23_0"><%= patient.getEmergencyContactNumber()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_16" class="richtext firer commentable">
				<div id="s-Rich_text_16-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_16_0"><%= patient.getDOB()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Rich_text_19" class="richtext firer commentable">
				<div id="s-Rich_text_19-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_19_0"><%= patient.getRegistrationDate()%></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</body>
</html>