<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ page import="model.Patient"%>
    <%@ page import="model.Appointment"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.servlet.http.HttpSession" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="private" />
<meta http-equiv="x-ua-Compatible" content="IE=edge" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta name="viewport"
	content="width=device-width, initial-scale=0.5, maximum-scale=5.0, user-scalable=1" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style"
	content="black-translucent" />
<meta name="author" content="Justinmind S.L." />
<meta name="description"
	content="Generated by Justinmind on Fri Nov 18 19:41:25 EST 2011" />
<title>project_Latest We_Care_2011-11-15_10h55m17s - View
	Patient Appointment</title>
</head>
<body>

<%
	ArrayList<Appointment> schedule = (ArrayList<Appointment>)session.getAttribute("schedule"); 

%>

	<div id="s-933424d3-b95c-46c7-939a-5a68984891a0">
		<input id="screenName" type="hidden" value="View Patient Appointment" /><input
			id="canvases" type="hidden"
			value="s-933424d3-b95c-46c7-939a-5a68984891a0?t-cc823e36-92f0-4b7b-b8e6-250fbacc84ac" />
		<link rel="stylesheet" charset="utf-8"
			href="css/screens/View%20Patient%20Appointment.css" />
		<link rel="stylesheet" charset="utf-8"
			href="css/templates/Doctor%20Template.css" />
		<!--[if IE]><link rel="stylesheet" charset="utf-8" href="css/screens/View%20Patient%20Appointment-ie.css"/><link rel="stylesheet" charset="utf-8" href="css/templates/Doctor%20Template-ie.css"/><![endif]-->
		<div
			class="t-cc823e36-92f0-4b7b-b8e6-250fbacc84ac template firer commentable">
			<img id="t-Image_1" class="image firer commentable" alt="image"
				src="images/79-%20jp_clipboard_image.png" />
			<div id="t-Line_1" class="horizontalline firer commentable"></div>
			<img id="t-Image_2" class="image firer commentable" alt="image"
				src="images/0-%20we%20care.gif" />
			<div id="t-Line_2" class="horizontalline firer commentable"></div>
			<div id="t-Label_2" class="label firer commentable">© 2011 We
				Care. All Rights Reserved</div>
			<form action="Logout" method="post">
			<div id="t-Button_8" class="button firer click commentable"><input type="submit" value="Logout" /></div></form>
			<form action="Doctor.html" method="post">
			<div id="t-Button_9" class="button firer click commentable"><input type="submit" value="Home" /></div></form>
		</div>
	<!--  	<div id="s-Label_8" class="label firer commentable">Patient	Name</div>
		<div id="s-Label_9" class="label firer commentable">Time</div>-->
		<div
			class="s-933424d3-b95c-46c7-939a-5a68984891a0 screen firer commentable">
			
			<% 
			    for (int i = 0; i < schedule.size(); i++) { %>
			<div id="s-Rich_text_<%= (i+3) %>" class="richtext firer commentable">
				<div id="s-Rich_text_<%= (i+3) %>-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_<%= (i+3) %>_0"><%= schedule.get(i).getTime()%> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp;<%= schedule.get(i).getPatientName() %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div> <% } %>
	<!--  		<div id="s-Line_1" class="horizontalline firer commentable"></div>
			<div id="s-Line_2" class="verticalline firer commentable"></div>-->
			<div id="s-Rich_text_2" class="richtext firer commentable">
				<div id="s-Rich_text_2-container">
					<table class="collapse" style="height: 100%; width: 100%;"
						summary="">
						<tbody>
							<tr>
								<td><span id="s-Rich_text_2_0"><%=(String)session.getAttribute("date") %></span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="s-Label_7" class="label firer commentable">Date</div>
			<img id="s-Image_2" class="image firer commentable" alt="image"
				src="images/0-%20aag70100v05_1_3.jpg" />
			<div id="s-Label_27" class="label firer commentable">Patient
				Appointments</div>
		</div>
	</div>
</body>
</html>